version: '2'
services:
  db-library-com:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      
  r-library-com:
    image: odoo:11.0 
    networks:
      - default
    links:
      - db-library-com:db
    tty: true
    volumes:
      - ./library/src:/mnt/extra-addons

  proxy:
    image: nginx
    links:
      - r-library-com:r-library-com
    volumes:
      - ./library/config/nginx:/etc/nginx/conf.d/
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80

volumes:
  db-library-com:
  r-library-com:
  proxy:
